export type {
  SiteContent,
  SiteImage,
  SiteMeta,
  SiteBranding,
  SiteBooking,
  SiteContact,
  SiteRoom,
  SiteHome,
  SiteGallery,
  SiteGalleryCategory,
  SiteLocation,
  SiteLocationHighlight,
  SiteAmenities,
  SiteAmenity,
  SiteContactPage,
} from "@/lib/validation/site-content";
